# config_list.yaml
model_configs:
  - "./config/model/yolox/yolox-s.yaml"

exp_configs:
  - "./config/experiment/single/train.yaml"

dataset_configs:
  - 'config/dataset/gen1/event_frame/single/aug/flip_dt_50.yaml'
  - 'config/dataset/gen1/event_frame/single/aug/flip_rotate_dt_50.yaml'
  - 'config/dataset/gen1/event_frame/single/aug/flip_zoom_dt_50.yaml'
  - 'config/dataset/gen1/event_frame/single/aug/rotate_dt_50.yaml'
  - 'config/dataset/gen1/event_frame/single/aug/rotate_zoom_dt_50.yaml'
  - 'config/dataset/gen1/event_frame/single/aug/zoom_dt_50.yaml'
  - 'config/dataset/gen1/event_frame/single/aug/zoom_in_dt_50.yaml'
  - 'config/dataset/gen1/event_frame/single/aug/zoom_out_dt_50.yaml'