# config_list.yaml
model_configs:
  - "./config/model/rvt_detector/rvt_frame.yaml"

exp_configs:
  - "./config/experiment/sequence/train.yaml"

dataset_configs:
  - "./config/dataset/gen1/event_frame/sequence/dt_10.yaml"
  - "./config/dataset/gen1/event_frame/sequence/dt_20.yaml"
  - "./config/dataset/gen1/event_frame/sequence/dt_33.yaml"
  - "./config/dataset/gen1/event_frame/sequence/dt_50.yaml"
