model:
  name: 'yolox-lstm'
  type: 'rnn'
  partition_split_32: 1
  
  backbone:
    name: 'darknet_lstm'
    darknet:
      name: 'darknet'
      depth: 0.33
      width: 0.5
      out_features: ["dark3", "dark4", "dark5"] #choose darknet outputs 'stem', 'dark 2 ~ 5'
      depthwise: false
      act: "silu"
    
    lstm:
      name: 'LSTM'
      dim: ???
      dws_conv: false
      dws_conv_only_hidden: true
      dws_conv_kernel_size: 3
      drop_cell_update: 0
  
  fpn:
    name: 'pafpn'
    depth: 0.33
    in_stages: ["dark3", "dark4", "dark5"]
    in_channels: ???
    depthwise: false
    act: "silu"


  head:
    name: 'yolox'
    num_classes: ???
    strides: ???
    in_channels: ???
    act: "silu"
    depthwise: false

  postprocess:
    conf_thre: 0.1
    nms_thre: 0.45
