dataset:
  name: gen1
  data_dir: './datasets/pre_gen1'
  orig_size: [240, 304]
  target_size: ???

  ev_representation: event_frame
  ev_delta_t: 33
  n_bins: 10


  train:
    access_mode: 'random' # 'stream' or 'random'
    sequence_length: 21

  
    guarantee_labels: false
    downsample_by_factor_2: false
    only_load_end_labels: false

    data_augmentation:
      prob_hflip: 0.5
      rotate:
        prob: 0.8
        min_angle_deg: -6
        max_angle_deg: 6
      zoom:
        prob: 0.8
        zoom_in:
          weight: 8
          factor:
            min: 1.0
            max: 1.5
        zoom_out:
          weight: 2
          factor:
            min: 1
            max: 1.2

  val:
    access_mode: 'stream' # 'stream' or 'random'
    sequence_length: 21

    guarantee_labels: false
    downsample_by_factor_2: false
    only_load_end_labels: false

  test:
    access_mode: 'stream' # 'stream' or 'random'
    sequence_length: 21

    guarantee_labels: false
    downsample_by_factor_2: false
    only_load_end_labels: false